flippy_blog: 1
flippy_head_blog: 1
flippy_show_empty_blog: 0
flippy_prev_label_blog: '[node:title]'
flippy_next_label_blog: '[node:title]'
flippy_first_last_blog: 0
flippy_first_label_blog: ''
flippy_last_label_blog: ''
flippy_loop_blog: 0
flippy_random_blog: 0
flippy_random_label_blog: ''
flippy_truncate_blog: ''
flippy_ellipse_blog: ''
flippy_press_swipe_blog: null
flippy_custom_sorting_blog: 1
flippy_sort_blog: created
flippy_order_blog: ASC
