<?php

/**
 * @file
 * Contains gravity_blocks.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gravity_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gravity_blocks module.
    case 'help.page.gravity_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Blocks for hikewithgravity.com.') . '</p>';
      return $output;

    default:
  }
}
